### ISSUE TITLE
Admin to-do items for CNCF Move

### ISSUE THREAD

**Issue by dholbach** [kubereboot/kured#634]
Part of the new infrastructure move will mean doing the following things:

- [x] get CNCF Service Desk access for the maintainers, and have `kured` set up as a project there (Ticket ID: CNCFSD-1404)
- [x] apply for 1password access to share credentials: https://github.com/1Password/1password-teams-open-source/pull/597
- [x] ask users to move to [CNCF Slack #kured](https://cloud-native.slack.com/archives/kured)
- [x] add Kured to CNCF Landscape
- [x] GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [ ]  Have added your project to https://github.com/cncf/contribute
- [x] Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork (https://github.com/cncf/artwork/pull/357)
- [x] Start on written, open governance? see https://contribute.cncf.io/maintainers/governance/
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)
- [ ] ... please add ...

**Comment by dholbach** [comment]
https://github.com/cncf/toc/issues/922

**Comment by evrardjp** [comment]
As this seems a large item of coordination, and #633 is basically also doing the same, would it make sense to merge the two lists into one? Gives better view on what to do. We can tag people on the different tasks. WDYT?
